### ISSUE TITLE
Choix composés

### ISSUE THREAD

**Issue by jordane-quincy** [jordane-quincy/M2_ProgrammationOrienteeAgents#2]
Hello boys,

Toujours sur la partie multi critères, Mr adam indique : 

> Ainsi le tri sur (cout et durée) pourra se faire en posant par exemple un demi de la différence sur le coût plus un demi de la différence sur la durée si l’on souhaite donner une pondération égale aux deux critères...

Donc j'ai implémenté de cette manière :
`Collections.sort(results, (j1, j2)->(int)((j1.getNormDuration()*0.5 + j1.getNormCost()*0.5) - (j2.getNormDuration()*0.5 + j2.getNormCost()*0.5)));`

Si c'est correct selon vous, n'hésitez pas à fermer cette issue ;-)

**Comment by JbRezidu** [comment]
Et ca c'est good aussi :)
